// Generated by Wrangler on Mon Jun 03 2024 17:47:24 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	S3_ACCESS_KEY_ID: string;
	S3_SECRET_ACCESS_KEY: string;
	CF_ACCOUNT_ID: string;
	BUCKET_NAME: string;
}
